# Generated by Django 4.0.2 on 2022-02-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name': 'Speciality', 'verbose_name_plural': 'Specialities'},
        ),
    ]
